import { LogMessage } from 'src/app/modules/shared/models/LogMessage';

export const fakeLogs: LogMessage[] = [
    {level:'info', message: `Ani Restore File Loaded`, timestamp:''},
    {level:'info', message: `Windrunner API server (ver 2) started on port 9876`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command find '/media'/ -mindepth 1 -maxdepth 2 -not -path '*/.*' \( -type d -o -type l \) -mtime -7 -printf "'%T@ %p'"`, timestamp:''},
    {level:'verbose', message: `Rejected token auth due to: Error retrieving ID Token from GoogleError: Request failed with status code 400`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command find "'/media/anime/Sword Art Online - Alicization - War of Underworld'/" -mindepth 1 -maxdepth 1 -not -path '*/.*' -type f -mtime -7`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command find "'/media/anime/Digimon Adventure (2020)'/" -mindepth 1 -maxdepth 1 -not -path '*/.*' -type f -mtime -7`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command find "'/media/anime/Kanojo, Okarishimasu'/" -mindepth 1 -maxdepth 1 -not -path '*/.*' -type f -mtime -7`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command find "'/media/anime/Isshuukan Friends'/" -mindepth 1 -maxdepth 1 -not -path '*/.*' -type f -mtime -7`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffprobe -v fatal -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 11 [1080p].mkv"`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffprobe -v fatal -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 11 [1080p].mkv"`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffprobe -v fatal -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 03 [1080p].mkv"`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffprobe -v fatal -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 04 [1080p].mkv"`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffmpeg -ss 00:09:09 -t 1 -i "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 11 [1080p].mkv" -s 426x240 -f mjpeg runtime-files/img/thumbs/ee108d91-1d4f-444c-b996-320f428168b9.jpg -y -loglevel error`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffmpeg -ss 00:02:17 -t 1 -i "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 11 [1080p].mkv" -s 426x240 -f mjpeg runtime-files/img/thumbs/c159fe27-6a60-4cd5-bf48-1603d6fa58a7.jpg -y -loglevel error`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffmpeg -ss 00:04:34 -t 1 -i "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 11 [1080p].mkv" -s 426x240 -f mjpeg runtime-files/img/thumbs/cfc47141-c709-49c5-b970-4141baddba80.jpg -y -loglevel error`, timestamp:''},
    {level:'verbose', message: `image compression complete for runtime-files/img/thumbs/6b034d66-a7bc-4ded-9a5b-9b52b7dd2696.jpg`, timestamp:''},
    {level:'verbose', message: `image compression complete for runtime-files/img/thumbs/3bf3f946-cc76-484e-85f1-0001f853de83.jpg`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffmpeg -ss 00:18:19 -t 1 -i "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 10 [1080p].mkv" -s 426x240 -f mjpeg runtime-files/img/thumbs/2600ca00-8e49-4c19-96dc-6ca48b390498.jpg -y -loglevel error`, timestamp:''},
    {level:'verbose', message: `image compression complete for runtime-files/img/thumbs/2600ca00-8e49-4c19-96dc-6ca48b390498.jpg`, timestamp:''},
    {level:'verbose', message: `executor command finished successfully for command ffmpeg -ss 00:22:54 -t 1 -i "/media/anime/Yahari Ore no Seishun Love Come wa Machigatteiru Kan/Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 10 [1080p].mkv" -s 426x240 -f mjpeg runtime-files/img/thumbs/bbfe962b-cabf-440a-8906-21d46be29443.jpg -y -loglevel error`, timestamp:''},
    {level:'verbose', message: `image compression complete for runtime-files/img/thumbs/bbfe962b-cabf-440a-8906-21d46be29443.jpg`, timestamp:''},
    {level:'verbose', message: `Little Busters! Refrain has evolved into SeriesDirectory`, timestamp:''},
    {level:'verbose', message: `PSYCHO-PASS 3 has evolved into SeriesDirectory`, timestamp:''},
    {level:'verbose', message: `God Eater has evolved into SeriesDirectory`, timestamp:''},
    {level:'verbose', message: `PSYCHO-PASS 2 has evolved into SeriesDirectory`, timestamp:''},
    {level:'verbose', message: `PSYCHO-PASS has evolved into SeriesDirectory`, timestamp:''},
    {level:'verbose', message: `Monogatari Series Second Season has evolved into SeriesDirectory`, timestamp:''},
    {level:'verbose', message: `PSYCHO-PASS 3 First Inspector has evolved into SeriesDirectory`, timestamp:''},
    {level:'verbose', message: `God Eater is now a series with pictures!`, timestamp:''},
    {level:'verbose', message: `Little Busters! Refrain is now a series with pictures!`, timestamp:''},
    {level:'verbose', message: `PSYCHO-PASS 2 is now a series with pictures!`, timestamp:''},
    {level:'verbose', message: `Monogatari Series Second Season is now a series with pictures!`, timestamp:''},
    {level:'verbose', message: `PSYCHO-PASS 3 is now a series with pictures!`, timestamp:''},
    {level:'verbose', message: `PSYCHO-PASS 3 First Inspector is now a series with pictures!`, timestamp:''},
    {level:'verbose', message: `PSYCHO-PASS is now a series with pictures!`, timestamp:''},
];